blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/alexfordlabs/project-architect/discussions
    about: Have a question or want to share a use case? Start a discussion.
